export const scheduleData = [
  {
    day: "Day 1",
    date: "13th March 2026",
    events: [
      {
        id: "d1-e1",
        time: "9:30 AM - 11:30 AM",
        title: "Inaugural Ceremony",
        location: "DPA",
        tags: ["Ceremony"],
      },
      {
        id: "d1-e2",
        time: "11:30 AM - 12:00 PM",
        title: "Tea & Networking Time",
        location: "OUTSIDE DPA",
        tags: ["Networking"],
      },
      {
        id: "d1-e3",
        time: "12:00 PM - 2:00 PM",
        title: "Exhibition By School Students",
        location: "NEAR I.T. BUILDING",
      },
      {
        id: "d1-e4",
        time: "12:00 PM - 2:00 PM",
        title: "TEXcelerate",
        location: "A-27",
      },
      {
        id: "d1-e5",
        time: "12:00 PM - 1:00 PM",
        title: "Equity Minds Offline Quiz",
        location: "A-26",
        tags: ["Competition"],
      },
      {
        id: "d1-e6",
        time: "12:00 PM - 1:30 PM",
        title: "Speaker Session 1",
        location: "C-51",
        tags: ["Speaker"],
      },
      {
        id: "d1-e7",
        time: "2:00 PM - 3:30 PM",
        title: "Lunch and Networking",
        location: "CAFETERIA",
        tags: ["Networking"],
      },
      {
        id: "d1-e8",
        time: "4:00 PM - 6:00 PM",
        title: "Workshop 1",
        location: "C-51",
        tags: ["Workshop"],
      },
      {
        id: "d1-e9",
        time: "4:00 PM - 5:30 PM",
        title: "TD Program",
        location: "A-27",
      },
      {
        id: "d1-e10",
        time: "5:30 PM - 6:00 PM",
        title: "Tea and Snacks",
        location: "OUTSIDE EVENT",
      },
      {
        id: "d1-e11",
        time: "11:00 PM",
        title: "INNOVATHON BEGINS",
        location: "A-27",
        tags: ["Special"],
      },
    ],
  },
  {
    day: "Day 2",
    date: "14th March 2026",
    events: [
      {
        id: "d2-e1",
        time: "8:00 AM - 9:30 AM",
        title: "Innovathon Breakfast",
        location: "CAFETERIA",
      },
      {
        id: "d2-e2",
        time: "10:00 AM - 12:30 PM",
        title: "Workshop 2",
        location: "C-51",
        tags: ["Workshop"],
      },
      {
        id: "d2-e3",
        time: "10:00 AM - 12:00 PM",
        title: "Being An Entrepreneur",
        location: "A-26",
        tags: ["Speaker"],
      },
      {
        id: "d2-e4",
        time: "2:00 PM - 3:30 PM",
        title: "Lunch and Networking (Innovathon Speaker)",
        location: "CAFETERIA",
        tags: ["Networking"],
      },
      {
        id: "d2-e5",
        time: "3:00 PM - 4:30 PM",
        title: "Speaker Session 2",
        location: "C-51",
        tags: ["Speaker"],
      },
      {
        id: "d2-e6",
        time: "3:30 PM - 5:00 PM",
        title: "Udaan UG Fellowship Program",
        location: "A-26",
      },
      {
        id: "d2-e7",
        time: "5:00 PM - 5:30 PM",
        title: "Tea & Network",
        location: "OUTSIDE EVENT",
        tags: ["Networking"],
      },
      {
        id: "d2-e8",
        time: "6:00 PM",
        title: "Gathering Together",
        location: "NEAR ADMIN",
        tags: ["Special"],
      },
    ],
  },
  {
    day: "Day 3",
    date: "15th March 2026",
    events: [
      {
        id: "d3-e1",
        time: "8:00 AM - 9:30 AM",
        title: "Breakfast — Innovathon Participants",
        location: "CAFETERIA",
      },
      {
        id: "d3-e2",
        time: "10:00 AM - 12:00 PM",
        title: "Ending of Innovathon & Final Judging Round",
        location: "A-27",
        tags: ["Competition"],
      },
      {
        id: "d3-e3",
        time: "10:00 AM - 2:00 PM",
        title: "Fun Activity",
        location: "NEAR PARKING",
      },
      {
        id: "d3-e4",
        time: "11:30 AM - 1:00 PM",
        title: "Equity Minds Finals",
        location: "A-26",
        tags: ["Competition"],
      },
      {
        id: "d3-e5",
        time: "1:30 PM - 2:30 PM",
        title: "Lunch and Networking",
        location: "CAFETERIA",
        tags: ["Networking"],
      },
      {
        id: "d3-e6",
        time: "3:00 PM - 5:00 PM",
        title: "Influencer Session",
        location: "DPA",
        tags: ["Speaker"],
      },
      {
        id: "d3-e7",
        time: "5:00 PM - 7:00 PM",
        title: "Closing Ceremony",
        location: "DPA",
        tags: ["Ceremony"],
      },
    ],
  },
];
