export const scheduleData = [
  {
    day: "Day 1",
    date: "17th April 2026",
    events: [
      {
        id: "d1-e1",
        time: "10:00 AM - 12:00 PM",
        title: "Inaugural Session",
        location: "C-51",
        faculty: "Prof. Mukesh Chandra, Dr. Rahul Kumar",
        tags: ["Ceremony"],
      },
      {
        id: "d1-e2",
        time: "12:00 PM - 2:00 PM",
        title: "Being an Entrepreneur",
        location: "A-26",
        faculty: "Dr. Abhijit Anand, Prof. Vijay Kumar Besra",
        tags: ["Speaker"],
      },
      {
        id: "d1-e3",
        time: "12:00 PM - 2:00 PM",
        title: "BuildX EXPO (School)",
        location: "Near IT Building",
        faculty: "Prof. (Dr.) R. K. Verma & Team",
        tags: ["Exhibition"],
      },
      {
        id: "d1-e4",
        time: "2:00 PM - 4:00 PM",
        title: "UDAAN Fellowship",
        location: "A-26",
        faculty: "Prof. Roshan Kumar",
        tags: [],
      },
      // {
      //   id: "d1-e5",
      //   time: "3:30 PM - 5:30 PM",
      //   title: "Speaker Session & Workshops (Workshop 1)",
      //   location: "C-51",
      //   faculty: "Dr. Rahul Kumar, Prof. Izhar Hussain",
      //   tags: ["Speaker", "Workshop"],
      // },
      {
        id: "d1-e5",
        time: "10:00 PM",
        title: "INNOVATHON (Begins)",
        location: "A-27",
        faculty:
          "Dr. Mukesh Chandra, Dr. Kashif Hasan Kazmi, Dr. Khustar Ansari",
        tags: ["Competition", "Special"],
      },
    ],
  },
  {
    day: "Day 2",
    date: "18th April 2026",
    events: [
      {
        id: "d2-e1",
        time: "9:00 AM - 11:00 AM",
        title: "Equity Minds (Quiz Round)",
        location: "A-26",
        faculty: "Prof. Sanjay Pal, Dr. Abhijit Anand",
        tags: ["Competition"],
      },
      {
        id: "d2-e2",
        time: "9:30 AM - 11:30 AM",
        title: "Speaker Session : SKILLS & MINDSET OF A YOUNG ENTREPRENEUR",
        location: "C-51",
        faculty: "Dr. Rahul Kumar, Prof. Izhar Hussain",
        tags: ["Speaker", "Workshop"],
      },
      {
        id: "d2-e3",
        time: "10:30 AM - 12:30 PM",
        title: "BuildX EXPO (College)",
        location: "Near IT Building",
        faculty: "Prof. (Dr.) R. K. Verma & Team",
        tags: ["Exhibition"],
      },
      {
        id: "d2-e4",
        time: "11:30 AM - 2:00 PM",
        title: "T.D. Project",
        location: "A-26",
        faculty: "Dr. Kashif Hasan Kazmi",
        tags: [],
      },
      {
        id: "d2-e5",
        time: "3:00 PM - 5:00 PM",
        title: "TEXcelerate",
        location: "A-27",
        faculty: "Dr. Biswranjan Mishra, Prof. Sanjay Pal",
        tags: [],
      },
      {
        id: "d2-e6",
        time: "3:00 PM - 5:00 PM",
        title: "Equity Minds (Round-2)",
        location: "A-26",
        faculty: "Prof. Sanjay Pal, Dr. Abhijit Anand",
        tags: ["Competition"],
      },
      // {
      //   id: "d2-e7",
      //   time: "3:30 PM - 5:30 PM",
      //   title: "Speaker Session & Workshops (Session 1)",
      //   location: "C-51",
      //   faculty: "Dr. Rahul Kumar, Prof. Izhar Hussain",
      //   tags: ["Speaker", "Workshop"],
      // },
    ],
  },
  {
    day: "Day 3",
    date: "19th April 2026",
    events: [
      {
        id: "d3-e1",
        time: "10:30 AM - 12:00 PM",
        title: "Speaker Session : BUILD DIGITAL EQUITY, NOT JUST EMPLOYMENT",
        location: "A-26",
        faculty: "Dr. Rahul Kumar, Prof. Izhar Hussain",
        tags: ["Speaker", "Workshop"],
      },
      {
        id: "d3-e2",
        time: "3:30 PM - 5:30 PM",
        title:
          "Influencer Session : EVERY REACTION HAS LOGIC; ONCE YOU SEE THE LOGIC, YOU'LL NEVER FORGET IT.",
        location: "C-51",
        faculty: "Dr. Rahul Kumar, Prof. Izhar Hussain",
        tags: ["Speaker"],
      },
      {
        id: "d3-e3",
        time: "7:00 PM",
        title: "Valedictory Session",
        location: "A-27",
        faculty: "Dr. Rahul Kumar, Prof. Izhar Hussain",
        tags: ["Speaker"],
      },
    ],
  },
];
